site_name: ""
site_url: https://gongjr0.github.io/NeoPortfolio/
site_author: Ege Güney Kıymaç

theme:
  name: windmill
  user_color_mode_toggle: true
  search_index_only: true
  include_search_page: true

nav:
  - Home: index.md
  - Quick Start: QuickStart.md
  - Portfolio: Portfolio.md
  - Markowitz: Markowitz.md
  - nCrOptimize: nCrOptimize.md
  - nCrResult: nCrResult.md
  - BtEngine: BtEngine.md
  - BtStrategy: BtStrategy.md

extra:
  article_nav_bottom: true
  logo: logo.png
  version: v1.3.0

markdown_extensions:
  - md4mathjax